### PR TITLE
Add jsonify dependency

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
This seems to be required for dev version of mapdeck. Heads-up @symbolixAU

**Comment by mpadge** [comment]
Strange, that shouldn't be needed because it's just a `LinkingTo`, not an `Imports`. Is it just because travis needs it? (Although that's hard to tell at present because r-travis is failing in general.)

**Comment by Robinlovelace** [comment]
Try `install_github("atfutures/upthat")` - it fails without this for me.

**Comment by mpadge** [comment]
`jsonify` is just in `LinkingTo` of `mapdeck`, and so is automatically installed with `mapdeck`. I checked in a clean docker container, which came up with an auto-install of CRAN `jsonify` = 1.0.0, but a dependency of `spatialwidget` on `jsonify >= 1.0.3`. This means that current `mapdeck` needs a `Remotes: jsonify`, and so ping @SymbolixAU - can you please amend accordingly, or update CRAN `jsonify` to >= 1.0.3 - thanks!

**Comment by SymbolixAU** [comment]
like [this](https://github.com/SymbolixAU/mapdeck/commit/ec8d3f2a7c1831addba65ac618845afc5d7124a7) (and [this](https://github.com/SymbolixAU/spatialwidget/commit/bbdbb73d168a7b1ce8030c9151d8eb33735d6920) ) ?

**Comment by mpadge** [comment]
Perfect - thanks! @robinlovelace this PR should no longer be necessary, right?

**Comment by Robinlovelace** [comment]
Correct.

**Pull request closed without merging**
