### PR TITLE
Close #37

### LINKED ISSUE #37: Hide UI elements that don't do anything

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @mpadge I'm planning to merge this soon.

**Review by mpadge — APPROVED** [review]
Ditching the sliders is good. This all works for me, and goes a long way towards what we need. Note we'll still be missing green space, which T seemed keen to have. I could still do that following 2 higher priority tasks: (1) Manuscript discussion; (2) Adaptation Manual. But (1) is going really well, so may well have time tomorrow - what do you think?

**Comment by Robinlovelace** [comment]
I think adding a new city is more important than adding green space.

**Comment by mpadge** [comment]
Agree. Plus green space would face similar issues to exposure, in being impossible to put an intelligible scale on

**Pull request merged**
